### ISSUE TITLE
Error: "settings" contains an invalid JSON: invalid character 'g' in string escape code

### ISSUE THREAD

**Issue by espi3030** [Yvand/AzureRM-Templates#25]
Attempting to deploy this environment with Terraform, but I get the above error.  Also the following description, and cannot locate where the problem is...

on SharePoint-ADFS.tf line 232, in resource "azurerm_virtual_machine_extension" "VM-DC-DSC":
 232: resource "azurerm_virtual_machine_extension" "VM-DC-DSC" {

**Comment by Yvand** [comment]
I didn't play with the Terraform template for a long time, so I just upgraded it to v0.12 in https://github.com/Yvand/AzureRM-Templates/tree/dev/Terraform/SharePoint-ADFS.
But for some reason, it hangs at creating network cards, I need to investigate this.
I'll update this thread when I have news

**Comment by espi3030** [comment]
Here are the latest errors I am receiving...

Error: Invalid index

  on SharePoint-ADFS.tf line 63, in resource "azurerm_network_security_group" "NSG-VNet-SP":
  63:   name                = "NSG-VNet-${var.vmSP["vmName"]}"
    |----------------
    | var.vmSP is map of string with 2 elements

The given key does not identify an element in this collection value.


Error: Invalid index

  on SharePoint-ADFS.tf line 117, in resource "azurerm_subnet" "Subnet-SP":
 117:   name                 = "Subnet-${var.vmSP["vmName"]}"
    |----------------
    | var.vmSP is map of string with 2 elements

The given key does not identify an element in this collection value.


Error: Invalid index

  on SharePoint-ADFS.tf line 175, in resource "azurerm_public_ip" "PublicIP-SP":
 175:   name                         = "PublicIP-${var.vmSP["vmName"]}"
    |----------------
    | var.vmSP is map of string with 2 elements

The given key does not identify an element in this collection value.


Error: Invalid index

  on SharePoint-ADFS.tf line 178, in resource "azurerm_public_ip" "PublicIP-SP":
 178:   domain_name_label            = "${lower(var.dnsLabelPrefix)}-${lower(var.vmSP["vmName"])}"
    |----------------
    | var.vmSP is map of string with 2 elements

The given key does not identify an element in this collection value.




Thank you,


[cid:f4144c86-bf17-4c51-9159-db5c1878d85d]

Alfred U. Espinosa

CIE Cloud Engineer

Smartronix Inc.



________________________________

**Comment by Yvand** [comment]
I also had this error, it's because variable vmSP was also set in the .tfvars file, if you remove it from the .tfvars file then it works.
Apparently this is due to this: https://www.terraform.io/upgrade-guides/0-12.html#map-variables-no-longer-merge-when-overridden

**Comment by Yvand** [comment]
About your original issue, the value of variable _artifactsLocation was incorrect, so the path to DSC files was invalid, which probably caused the issue
